const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{"content-type":"application/json; charset=utf-8","cache-control":"no-store"}});
const uid=()=>crypto.randomUUID();
const enc=new TextEncoder();
const b64=s=>btoa(String.fromCharCode(...new Uint8Array(s))).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/,"");
async function signToken(email,secret){const key=await crypto.subtle.importKey("raw",enc.encode(secret),{name:"HMAC",hash:"SHA-256"},false,["sign"]);const sig=await crypto.subtle.sign("HMAC",key,enc.encode(email));return btoa(email)+"."+b64(sig)}
async function validToken(req,env){const h=req.headers.get("authorization")||"";if(!h.startsWith("Bearer "))return false;const token=h.slice(7);const [a,sig]=token.split(".");if(!a||!sig)return false;const email=atob(a);try{await env.DB.prepare("CREATE TABLE IF NOT EXISTS admin_users(id TEXT PRIMARY KEY,email TEXT UNIQUE NOT NULL,password_hash TEXT NOT NULL,salt TEXT NOT NULL,session_secret TEXT NOT NULL,created_at TEXT DEFAULT CURRENT_TIMESTAMP)").run();const u=await env.DB.prepare("SELECT email,session_secret FROM admin_users WHERE email=? LIMIT 1").bind(email).first();if(!u)return false;const expected=await signToken(email,u.session_secret);return token===expected}catch{return false}}
async function hashPassword(password,salt){const key=await crypto.subtle.importKey("raw",enc.encode(password),"PBKDF2",false,["deriveBits"]);const bits=await crypto.subtle.deriveBits({name:"PBKDF2",salt:enc.encode(salt),iterations:100000,hash:"SHA-256"},key,256);return b64(bits)}
const setupPage=(req)=>{const token=new URL(req.url).searchParams.get("token")||"";const t=JSON.stringify(token);const html=`<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>THEJU SALES Admin Setup</title><style>body{margin:0;background:#f5f1e8;font-family:Arial,sans-serif;color:#102a24;display:grid;place-items:center;min-height:100vh}.box{background:white;width:min(92%,460px);padding:32px;border-radius:18px;box-shadow:0 15px 50px #0002}h1{font-family:Georgia;font-size:42px;margin:10px 0}label{display:block;font-weight:700;margin:18px 0 7px}input{box-sizing:border-box;width:100%;padding:15px;border:1px solid #ddd;border-radius:8px;font-size:16px}button{width:100%;padding:16px;margin-top:22px;border:0;border-radius:8px;background:#0d4035;color:white;font-size:17px;font-weight:700}small{color:#777}.msg{margin-top:15px;font-weight:700}</style></head><body><form class="box" id="f"><small>THEJU SALES • ONE-TIME SETUP</small><h1>Create Admin</h1><p>Create your private admin account. This setup can be completed only once.</p><label>Email</label><input id="email" type="email" value="thejuthejwal870@gmail.com" required><label>New Password</label><input id="password" type="password" minlength="10" required placeholder="At least 10 characters"><button>Create Admin</button><div class="msg" id="m"></div></form><script>f.onsubmit=async e=>{e.preventDefault();const r=await fetch("/api/admin/setup",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({token:TOKEN,email:email.value,password:password.value})});const d=await r.json();m.textContent=d.error||"Admin created successfully. Open /admin to login.";if(r.ok)setTimeout(()=>location.href="/admin",1000)}</script></body></html>`.replace("TOKEN",t);return new Response(html,{headers:{"content-type":"text/html;charset=UTF-8","cache-control":"no-store"}})};
async function api(req,env,url){
  if(url.pathname==="/api/products"&&req.method==="GET"){const {results}=await env.DB.prepare("SELECT * FROM products WHERE is_active=1 ORDER BY created_at DESC").all();return json(results||[])}
  if(url.pathname==="/api/orders/has-phone"&&req.method==="GET"){const phone=url.searchParams.get("phone")||"";const row=await env.DB.prepare("SELECT id FROM orders WHERE phone=? LIMIT 1").bind(phone).first();return json({exists:!!row})}
  if(url.pathname==="/api/orders"&&req.method==="POST"){const body=await req.json();if(!body?.customer_first_name||!body?.phone||!body?.address||!body?.pin_code||!Array.isArray(body.items)||!body.items.length)return json({error:"Missing order details"},400);const id=uid();await env.DB.batch([env.DB.prepare("INSERT INTO orders(id,order_number,customer_first_name,customer_last_name,phone,address,pin_code,payment_method,status,total) VALUES(?,?,?,?,?,?,?,?,?,?)").bind(id,body.order_number,body.customer_first_name,body.customer_last_name||"",body.phone,body.address,body.pin_code,"COD","pending",Number(body.total)||0),...body.items.map(i=>env.DB.prepare("INSERT INTO order_items(id,order_id,product_id,product_name,price,quantity) VALUES(?,?,?,?,?,?)").bind(uid(),id,i.product_id||null,i.product_name,Number(i.price)||0,Number(i.quantity)||1))]);return json({ok:true,id,order_number:body.order_number})}
  if(url.pathname==="/api/admin/setup"&&req.method==="POST"){const b=await req.json();const setupHash="888223c2b861405acb96af042add11d7af8d000f285bb7ac8102a2b334279568";const token=String(b.token||"");const digest=await crypto.subtle.digest("SHA-256",enc.encode(token));const got=Array.from(new Uint8Array(digest)).map(x=>x.toString(16).padStart(2,"0")).join("");if(got!==setupHash)return json({error:"Invalid setup link"},403);if(!b.email||!b.password||String(b.password).length<10)return json({error:"Use a password with at least 10 characters"},400);await env.DB.prepare("CREATE TABLE IF NOT EXISTS admin_users(id TEXT PRIMARY KEY,email TEXT UNIQUE NOT NULL,password_hash TEXT NOT NULL,salt TEXT NOT NULL,session_secret TEXT NOT NULL,created_at TEXT DEFAULT CURRENT_TIMESTAMP)").run();const existing=await env.DB.prepare("SELECT id FROM admin_users LIMIT 1").first();if(existing)return json({error:"Admin is already configured. Use the Admin Login."},409);const salt=crypto.randomUUID()+"-"+crypto.randomUUID();const passwordHash=await hashPassword(b.password,salt);const sessionSecret=crypto.randomUUID()+"-"+crypto.randomUUID();await env.DB.prepare("INSERT INTO admin_users(id,email,password_hash,salt,session_secret) VALUES(?,?,?,?,?)").bind(uid(),String(b.email).trim().toLowerCase(),passwordHash,salt,sessionSecret).run();return json({ok:true})}
  if(url.pathname==="/api/admin/login"&&req.method==="POST"){const b=await req.json();await env.DB.prepare("CREATE TABLE IF NOT EXISTS admin_users(id TEXT PRIMARY KEY,email TEXT UNIQUE NOT NULL,password_hash TEXT NOT NULL,salt TEXT NOT NULL,session_secret TEXT NOT NULL,created_at TEXT DEFAULT CURRENT_TIMESTAMP)").run();const email=String(b.email||"").trim().toLowerCase();const u=await env.DB.prepare("SELECT * FROM admin_users WHERE email=? LIMIT 1").bind(email).first();if(!u)return json({error:"Invalid admin login"},401);const passwordHash=await hashPassword(String(b.password||""),u.salt);if(passwordHash!==u.password_hash)return json({error:"Invalid admin login"},401);return json({token:await signToken(email,u.session_secret)})}
  if(url.pathname==="/api/admin/orders"&&req.method==="GET"){if(!await validToken(req,env))return json({error:"Unauthorized"},401);const {results}=await env.DB.prepare("SELECT * FROM orders ORDER BY created_at DESC").all();for(const o of results||[]){const r=await env.DB.prepare("SELECT * FROM order_items WHERE order_id=? ORDER BY created_at").bind(o.id).all();o.order_items=r.results||[]}return json(results||[])}
  if(url.pathname.startsWith("/api/admin/orders/")&&req.method==="PATCH"){if(!await validToken(req,env))return json({error:"Unauthorized"},401);const id=url.pathname.split("/").pop();const b=await req.json();await env.DB.prepare("UPDATE orders SET status=?,updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(b.status,id).run();return json({ok:true})}
  if(url.pathname==="/api/admin/products"&&req.method==="POST"){if(!await validToken(req,env))return json({error:"Unauthorized"},401);const b=await req.json();await env.DB.prepare("INSERT INTO products(id,name,description,category,price,old_price,stock,image_url,is_active) VALUES(?,?,?,?,?,?,?,?,?)").bind(uid(),b.name,b.description||"",b.category||"Featured",Number(b.price)||0,b.old_price==null?null:Number(b.old_price),Number(b.stock)||0,b.image_url||"",1).run();return json({ok:true})}
  return null
}
export default{async fetch(req,env){const url=new URL(req.url);if(url.pathname==="/admin/setup"&&req.method==="GET")return setupPage(req);if(url.pathname.startsWith("/api/")){try{const r=await api(req,env,url);return r||json({error:"Not found"},404)}catch(e){return json({error:e.message||"Server error"},500)}}let asset=await env.ASSETS.fetch(req);if(asset.status===404&&(url.pathname==="/admin"||url.pathname==="/admin/setup")){asset=await env.ASSETS.fetch(new Request(new URL("/",req.url),req))}return asset}};