const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{"content-type":"application/json; charset=utf-8","cache-control":"no-store"}});
const uid=()=>crypto.randomUUID();
const enc=new TextEncoder();
const b64=s=>btoa(String.fromCharCode(...new Uint8Array(s))).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/,"");
async function signToken(email,secret){const key=await crypto.subtle.importKey("raw",enc.encode(secret),{name:"HMAC",hash:"SHA-256"},false,["sign"]);const sig=await crypto.subtle.sign("HMAC",key,enc.encode(email));return btoa(email)+"."+b64(sig)}
async function validToken(req,env){const h=req.headers.get("authorization")||"";if(!h.startsWith("Bearer "))return false;const token=h.slice(7);const [a,sig]=token.split(".");if(!a||!sig)return false;const email=atob(a);if(email!==env.ADMIN_EMAIL)return false;const expected=await signToken(email,env.ADMIN_SECRET||"change-me");return token===expected}
async function api(req,env,url){
  if(url.pathname==="/api/products"&&req.method==="GET"){const {results}=await env.DB.prepare("SELECT * FROM products WHERE is_active=1 ORDER BY created_at DESC").all();return json(results||[])}
  if(url.pathname==="/api/orders/has-phone"&&req.method==="GET"){const phone=url.searchParams.get("phone")||"";const row=await env.DB.prepare("SELECT id FROM orders WHERE phone=? LIMIT 1").bind(phone).first();return json({exists:!!row})}
  if(url.pathname==="/api/orders"&&req.method==="POST"){const body=await req.json();if(!body?.customer_first_name||!body?.phone||!body?.address||!body?.pin_code||!Array.isArray(body.items)||!body.items.length)return json({error:"Missing order details"},400);const id=uid();await env.DB.batch([env.DB.prepare("INSERT INTO orders(id,order_number,customer_first_name,customer_last_name,phone,address,pin_code,payment_method,status,total) VALUES(?,?,?,?,?,?,?,?,?,?)").bind(id,body.order_number,body.customer_first_name,body.customer_last_name||"",body.phone,body.address,body.pin_code,"COD","pending",Number(body.total)||0),...body.items.map(i=>env.DB.prepare("INSERT INTO order_items(id,order_id,product_id,product_name,price,quantity) VALUES(?,?,?,?,?,?)").bind(uid(),id,i.product_id||null,i.product_name,Number(i.price)||0,Number(i.quantity)||1))]);return json({ok:true,id,order_number:body.order_number})}
  if(url.pathname==="/api/admin/login"&&req.method==="POST"){const b=await req.json();if(!env.ADMIN_EMAIL||!env.ADMIN_PASSWORD||!env.ADMIN_SECRET)return json({error:"Admin secrets are not configured in Cloudflare yet."},503);if(b.email!==env.ADMIN_EMAIL||b.password!==env.ADMIN_PASSWORD)return json({error:"Invalid admin login"},401);return json({token:await signToken(env.ADMIN_EMAIL,env.ADMIN_SECRET)})}
  if(url.pathname==="/api/admin/orders"&&req.method==="GET"){if(!await validToken(req,env))return json({error:"Unauthorized"},401);const {results}=await env.DB.prepare("SELECT * FROM orders ORDER BY created_at DESC").all();for(const o of results||[]){const r=await env.DB.prepare("SELECT * FROM order_items WHERE order_id=? ORDER BY created_at").bind(o.id).all();o.order_items=r.results||[]}return json(results||[])}
  if(url.pathname.startsWith("/api/admin/orders/")&&req.method==="PATCH"){if(!await validToken(req,env))return json({error:"Unauthorized"},401);const id=url.pathname.split("/").pop();const b=await req.json();await env.DB.prepare("UPDATE orders SET status=?,updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(b.status,id).run();return json({ok:true})}
  if(url.pathname==="/api/admin/products"&&req.method==="POST"){if(!await validToken(req,env))return json({error:"Unauthorized"},401);const b=await req.json();await env.DB.prepare("INSERT INTO products(id,name,description,category,price,old_price,stock,image_url,is_active) VALUES(?,?,?,?,?,?,?,?,?)").bind(uid(),b.name,b.description||"",b.category||"Featured",Number(b.price)||0,b.old_price==null?null:Number(b.old_price),Number(b.stock)||0,b.image_url||"",1).run();return json({ok:true})}
  return null
}
export default{async fetch(req,env){const url=new URL(req.url);if(url.pathname.startsWith("/api/")){try{const r=await api(req,env,url);return r||json({error:"Not found"},404)}catch(e){return json({error:e.message||"Server error"},500)}}return env.ASSETS.fetch(req)}};